### ISSUE TITLE
当ipv4地址改变后，定位无法更新

### ISSUE THREAD

**Issue by Emin-Zhang** [shaonianzhentan/ha_app#1]
我是openwrt中的docker运行的ha，所属地是移动大内网，Ipv4非公网且会不定期更换，每次更换都会导致定位不更新，报错如图：
![image](https://user-images.githubusercontent.com/61353294/232656987-59c3637d-df9a-4f79-8958-996f7cd54e87.png)

此时我ipv4实际是：
![111](https://user-images.githubusercontent.com/61353294/232656881-f91a0936-3367-4842-beae-1a143aa6bef8.png)

**Comment by shaonianzhentan** [comment]
代码设计没问题，请自行固定IP

**Comment by Emin-Zhang** [comment]
好的，谢谢。
